FROM node:18 as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
# השלב ה1 מקפל את כל קבצי הTSX/TS לקבצים סטטיים
# לוקח את הקבצים ששמרנו עד עכשיו מהתיקיית dist ושומר בתקייה אחרת של NGINX 
# מעכשיו עובדים עם שרת אינטרנט NGINX - עם גירסה מצומצמת
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]